inherit_from:
    - .rubocop_airbnb.yml

AllCops:
  TargetRubyVersion: 2.7
  DisabledByDefault: true
  Exclude:
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - '**/bin/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'actionmailbox/test/dummy/**/*'
    - 'actiontext/test/dummy/**/*'
    - '**/node_modules/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false