name: Deploy

on:
  push:
    branches:
      - master

env:
  RUBY_VERSION: 2.7.2
  PGHOST: localhost
  PGUSER: postgres
  RAILS_ENV: test
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle config set without 'default test'
          bundle install --jobs 4 --retry 3

      - name: Run RuboCop
        run: bundle exec rubocop --require rubocop-airbnb

  rspec:
    name: rspec
    needs: rubocop
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Install postgres client
        run: sudo apt-get install libpq-dev

      - name: Install dependencies
        run: |
          gem install bundler
          bundler install --jobs 4 --retry 3

      - name: Prepare database
        run: |
          bundle exec rake db:prepare

      - name: Run tests
        run: bundle exec rspec

  release:
    name: release
    needs: rspec
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}